/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpringHopeRouteImport } from './routes/spring-hope'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as ApiFormsRouteImport } from './routes/api.forms'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiSubmissionsRouteImport } from './routes/api.submissions'
import { Route as IntakeIndexRouteImport } from './routes/intake.index'
import { Route as IntakeCompleteRouteImport } from './routes/intake.complete'
import { Route as IntakeMicrophoneRouteImport } from './routes/intake.microphone'
import { Route as IntakeQuestionRouteImport } from './routes/intake.question'
import { Route as AdminFormsBuilderIndexRouteImport } from './routes/admin.forms-builder.index'
import { Route as AdminFormsBuilderPublishRouteImport } from './routes/admin.forms-builder.publish'
import { Route as AdminNewAiRouteImport } from './routes/admin.new.ai'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api.admin.logout'
import { Route as ApiAdminStatusRouteImport } from './routes/api.admin.status'
import { Route as ApiAiExtractImageRouteImport } from './routes/api.ai.extract-image'
import { Route as ApiAiExtractPdfRouteImport } from './routes/api.ai.extract-pdf'
import { Route as ApiAiFormDraftRouteImport } from './routes/api.ai.form-draft'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthSetupRouteImport } from './routes/api.auth.setup'
import { Route as ApiAuthStatusRouteImport } from './routes/api.auth.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpringHopeRoute = SpringHopeRouteImport.update({
  id: '/spring-hope',
  path: '/spring-hope',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsRoute = ApiFormsRouteImport.update({
  id: '/api/forms',
  path: '/api/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsRoute = ApiSubmissionsRouteImport.update({
  id: '/api/submissions',
  path: '/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeCompleteRoute = IntakeCompleteRouteImport.update({
  id: '/intake/complete',
  path: '/intake/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeMicrophoneRoute = IntakeMicrophoneRouteImport.update({
  id: '/intake/microphone',
  path: '/intake/microphone',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeQuestionRoute = IntakeQuestionRouteImport.update({
  id: '/intake/question',
  path: '/intake/question',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsBuilderIndexRoute = AdminFormsBuilderIndexRouteImport.update({
  id: '/admin/forms-builder/',
  path: '/admin/forms-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsBuilderPublishRoute =
  AdminFormsBuilderPublishRouteImport.update({
    id: '/admin/forms-builder/publish',
    path: '/admin/forms-builder/publish',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNewAiRoute = AdminNewAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminNewRoute,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatusRoute = ApiAdminStatusRouteImport.update({
  id: '/api/admin/status',
  path: '/api/admin/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExtractImageRoute = ApiAiExtractImageRouteImport.update({
  id: '/api/ai/extract-image',
  path: '/api/ai/extract-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExtractPdfRoute = ApiAiExtractPdfRouteImport.update({
  id: '/api/ai/extract-pdf',
  path: '/api/ai/extract-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFormDraftRoute = ApiAiFormDraftRouteImport.update({
  id: '/api/ai/form-draft',
  path: '/api/ai/form-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetupRoute = ApiAuthSetupRouteImport.update({
  id: '/api/auth/setup',
  path: '/api/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spring-hope': typeof SpringHopeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/api/forms': typeof ApiFormsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/intake/complete': typeof IntakeCompleteRoute
  '/intake/microphone': typeof IntakeMicrophoneRoute
  '/intake/question': typeof IntakeQuestionRoute
  '/admin/': typeof AdminIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/admin/forms-builder/publish': typeof AdminFormsBuilderPublishRoute
  '/admin/new/ai': typeof AdminNewAiRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/ai/extract-image': typeof ApiAiExtractImageRoute
  '/api/ai/extract-pdf': typeof ApiAiExtractPdfRoute
  '/api/ai/form-draft': typeof ApiAiFormDraftRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/admin/forms-builder/': typeof AdminFormsBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spring-hope': typeof SpringHopeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/api/forms': typeof ApiFormsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/intake/complete': typeof IntakeCompleteRoute
  '/intake/microphone': typeof IntakeMicrophoneRoute
  '/intake/question': typeof IntakeQuestionRoute
  '/admin': typeof AdminIndexRoute
  '/intake': typeof IntakeIndexRoute
  '/admin/forms-builder/publish': typeof AdminFormsBuilderPublishRoute
  '/admin/new/ai': typeof AdminNewAiRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/ai/extract-image': typeof ApiAiExtractImageRoute
  '/api/ai/extract-pdf': typeof ApiAiExtractPdfRoute
  '/api/ai/form-draft': typeof ApiAiFormDraftRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/admin/forms-builder': typeof AdminFormsBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spring-hope': typeof SpringHopeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/api/forms': typeof ApiFormsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/intake/complete': typeof IntakeCompleteRoute
  '/intake/microphone': typeof IntakeMicrophoneRoute
  '/intake/question': typeof IntakeQuestionRoute
  '/admin/': typeof AdminIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/admin/forms-builder/publish': typeof AdminFormsBuilderPublishRoute
  '/admin/new/ai': typeof AdminNewAiRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/ai/extract-image': typeof ApiAiExtractImageRoute
  '/api/ai/extract-pdf': typeof ApiAiExtractPdfRoute
  '/api/ai/form-draft': typeof ApiAiFormDraftRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/admin/forms-builder/': typeof AdminFormsBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/spring-hope'
    | '/admin/login'
    | '/admin/new'
    | '/api/forms'
    | '/api/health'
    | '/api/submissions'
    | '/intake/complete'
    | '/intake/microphone'
    | '/intake/question'
    | '/admin/'
    | '/intake/'
    | '/admin/forms-builder/publish'
    | '/admin/new/ai'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/status'
    | '/api/ai/extract-image'
    | '/api/ai/extract-pdf'
    | '/api/ai/form-draft'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/auth/status'
    | '/admin/forms-builder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/spring-hope'
    | '/admin/login'
    | '/admin/new'
    | '/api/forms'
    | '/api/health'
    | '/api/submissions'
    | '/intake/complete'
    | '/intake/microphone'
    | '/intake/question'
    | '/admin'
    | '/intake'
    | '/admin/forms-builder/publish'
    | '/admin/new/ai'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/status'
    | '/api/ai/extract-image'
    | '/api/ai/extract-pdf'
    | '/api/ai/form-draft'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/auth/status'
    | '/admin/forms-builder'
  id:
    | '__root__'
    | '/'
    | '/spring-hope'
    | '/admin/login'
    | '/admin/new'
    | '/api/forms'
    | '/api/health'
    | '/api/submissions'
    | '/intake/complete'
    | '/intake/microphone'
    | '/intake/question'
    | '/admin/'
    | '/intake/'
    | '/admin/forms-builder/publish'
    | '/admin/new/ai'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/status'
    | '/api/ai/extract-image'
    | '/api/ai/extract-pdf'
    | '/api/ai/form-draft'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/setup'
    | '/api/auth/status'
    | '/admin/forms-builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpringHopeRoute: typeof SpringHopeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRouteWithChildren
  ApiFormsRoute: typeof ApiFormsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSubmissionsRoute: typeof ApiSubmissionsRoute
  IntakeCompleteRoute: typeof IntakeCompleteRoute
  IntakeMicrophoneRoute: typeof IntakeMicrophoneRoute
  IntakeQuestionRoute: typeof IntakeQuestionRoute
  AdminIndexRoute: typeof AdminIndexRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
  AdminFormsBuilderPublishRoute: typeof AdminFormsBuilderPublishRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminStatusRoute: typeof ApiAdminStatusRoute
  ApiAiExtractImageRoute: typeof ApiAiExtractImageRoute
  ApiAiExtractPdfRoute: typeof ApiAiExtractPdfRoute
  ApiAiFormDraftRoute: typeof ApiAiFormDraftRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSetupRoute: typeof ApiAuthSetupRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  AdminFormsBuilderIndexRoute: typeof AdminFormsBuilderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spring-hope': {
      id: '/spring-hope'
      path: '/spring-hope'
      fullPath: '/spring-hope'
      preLoaderRoute: typeof SpringHopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms': {
      id: '/api/forms'
      path: '/api/forms'
      fullPath: '/api/forms'
      preLoaderRoute: typeof ApiFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions': {
      id: '/api/submissions'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/complete': {
      id: '/intake/complete'
      path: '/intake/complete'
      fullPath: '/intake/complete'
      preLoaderRoute: typeof IntakeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/microphone': {
      id: '/intake/microphone'
      path: '/intake/microphone'
      fullPath: '/intake/microphone'
      preLoaderRoute: typeof IntakeMicrophoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/question': {
      id: '/intake/question'
      path: '/intake/question'
      fullPath: '/intake/question'
      preLoaderRoute: typeof IntakeQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms-builder/': {
      id: '/admin/forms-builder/'
      path: '/admin/forms-builder'
      fullPath: '/admin/forms-builder/'
      preLoaderRoute: typeof AdminFormsBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms-builder/publish': {
      id: '/admin/forms-builder/publish'
      path: '/admin/forms-builder/publish'
      fullPath: '/admin/forms-builder/publish'
      preLoaderRoute: typeof AdminFormsBuilderPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new/ai': {
      id: '/admin/new/ai'
      path: '/ai'
      fullPath: '/admin/new/ai'
      preLoaderRoute: typeof AdminNewAiRouteImport
      parentRoute: typeof AdminNewRoute
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/status': {
      id: '/api/admin/status'
      path: '/api/admin/status'
      fullPath: '/api/admin/status'
      preLoaderRoute: typeof ApiAdminStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/extract-image': {
      id: '/api/ai/extract-image'
      path: '/api/ai/extract-image'
      fullPath: '/api/ai/extract-image'
      preLoaderRoute: typeof ApiAiExtractImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/extract-pdf': {
      id: '/api/ai/extract-pdf'
      path: '/api/ai/extract-pdf'
      fullPath: '/api/ai/extract-pdf'
      preLoaderRoute: typeof ApiAiExtractPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/form-draft': {
      id: '/api/ai/form-draft'
      path: '/api/ai/form-draft'
      fullPath: '/api/ai/form-draft'
      preLoaderRoute: typeof ApiAiFormDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/setup': {
      id: '/api/auth/setup'
      path: '/api/auth/setup'
      fullPath: '/api/auth/setup'
      preLoaderRoute: typeof ApiAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminNewRouteChildren {
  AdminNewAiRoute: typeof AdminNewAiRoute
}

const AdminNewRouteChildren: AdminNewRouteChildren = {
  AdminNewAiRoute: AdminNewAiRoute,
}

const AdminNewRouteWithChildren = AdminNewRoute._addFileChildren(
  AdminNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpringHopeRoute: SpringHopeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRouteWithChildren,
  ApiFormsRoute: ApiFormsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSubmissionsRoute: ApiSubmissionsRoute,
  IntakeCompleteRoute: IntakeCompleteRoute,
  IntakeMicrophoneRoute: IntakeMicrophoneRoute,
  IntakeQuestionRoute: IntakeQuestionRoute,
  AdminIndexRoute: AdminIndexRoute,
  IntakeIndexRoute: IntakeIndexRoute,
  AdminFormsBuilderPublishRoute: AdminFormsBuilderPublishRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminStatusRoute: ApiAdminStatusRoute,
  ApiAiExtractImageRoute: ApiAiExtractImageRoute,
  ApiAiExtractPdfRoute: ApiAiExtractPdfRoute,
  ApiAiFormDraftRoute: ApiAiFormDraftRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSetupRoute: ApiAuthSetupRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  AdminFormsBuilderIndexRoute: AdminFormsBuilderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
