/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as IntakeIndexRouteImport } from './routes/intake.index'
import { Route as IntakeCompleteRouteImport } from './routes/intake.complete'
import { Route as IntakeMicrophoneRouteImport } from './routes/intake.microphone'
import { Route as IntakeQuestionRouteImport } from './routes/intake.question'
import { Route as AdminFormsBuilderIndexRouteImport } from './routes/admin.forms-builder.index'
import { Route as AdminFormsBuilderPublishRouteImport } from './routes/admin.forms-builder.publish'
import { Route as AdminNewAiRouteImport } from './routes/admin.new.ai'
import { Route as ApiAiExtractImageRouteImport } from './routes/api.ai.extract-image'
import { Route as ApiAiExtractPdfRouteImport } from './routes/api.ai.extract-pdf'
import { Route as ApiAiFormDraftRouteImport } from './routes/api.ai.form-draft'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeCompleteRoute = IntakeCompleteRouteImport.update({
  id: '/intake/complete',
  path: '/intake/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeMicrophoneRoute = IntakeMicrophoneRouteImport.update({
  id: '/intake/microphone',
  path: '/intake/microphone',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeQuestionRoute = IntakeQuestionRouteImport.update({
  id: '/intake/question',
  path: '/intake/question',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsBuilderIndexRoute = AdminFormsBuilderIndexRouteImport.update({
  id: '/admin/forms-builder/',
  path: '/admin/forms-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsBuilderPublishRoute =
  AdminFormsBuilderPublishRouteImport.update({
    id: '/admin/forms-builder/publish',
    path: '/admin/forms-builder/publish',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNewAiRoute = AdminNewAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminNewRoute,
} as any)
const ApiAiExtractImageRoute = ApiAiExtractImageRouteImport.update({
  id: '/api/ai/extract-image',
  path: '/api/ai/extract-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExtractPdfRoute = ApiAiExtractPdfRouteImport.update({
  id: '/api/ai/extract-pdf',
  path: '/api/ai/extract-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFormDraftRoute = ApiAiFormDraftRouteImport.update({
  id: '/api/ai/form-draft',
  path: '/api/ai/form-draft',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/intake/complete': typeof IntakeCompleteRoute
  '/intake/microphone': typeof IntakeMicrophoneRoute
  '/intake/question': typeof IntakeQuestionRoute
  '/admin/': typeof AdminIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/admin/forms-builder/publish': typeof AdminFormsBuilderPublishRoute
  '/admin/new/ai': typeof AdminNewAiRoute
  '/api/ai/extract-image': typeof ApiAiExtractImageRoute
  '/api/ai/extract-pdf': typeof ApiAiExtractPdfRoute
  '/api/ai/form-draft': typeof ApiAiFormDraftRoute
  '/admin/forms-builder/': typeof AdminFormsBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/intake/complete': typeof IntakeCompleteRoute
  '/intake/microphone': typeof IntakeMicrophoneRoute
  '/intake/question': typeof IntakeQuestionRoute
  '/admin': typeof AdminIndexRoute
  '/intake': typeof IntakeIndexRoute
  '/admin/forms-builder/publish': typeof AdminFormsBuilderPublishRoute
  '/admin/new/ai': typeof AdminNewAiRoute
  '/api/ai/extract-image': typeof ApiAiExtractImageRoute
  '/api/ai/extract-pdf': typeof ApiAiExtractPdfRoute
  '/api/ai/form-draft': typeof ApiAiFormDraftRoute
  '/admin/forms-builder': typeof AdminFormsBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/intake/complete': typeof IntakeCompleteRoute
  '/intake/microphone': typeof IntakeMicrophoneRoute
  '/intake/question': typeof IntakeQuestionRoute
  '/admin/': typeof AdminIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/admin/forms-builder/publish': typeof AdminFormsBuilderPublishRoute
  '/admin/new/ai': typeof AdminNewAiRoute
  '/api/ai/extract-image': typeof ApiAiExtractImageRoute
  '/api/ai/extract-pdf': typeof ApiAiExtractPdfRoute
  '/api/ai/form-draft': typeof ApiAiFormDraftRoute
  '/admin/forms-builder/': typeof AdminFormsBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/admin/new'
    | '/api/health'
    | '/intake/complete'
    | '/intake/microphone'
    | '/intake/question'
    | '/admin/'
    | '/intake/'
    | '/admin/forms-builder/publish'
    | '/admin/new/ai'
    | '/api/ai/extract-image'
    | '/api/ai/extract-pdf'
    | '/api/ai/form-draft'
    | '/admin/forms-builder/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/new'
    | '/api/health'
    | '/intake/complete'
    | '/intake/microphone'
    | '/intake/question'
    | '/admin'
    | '/intake'
    | '/admin/forms-builder/publish'
    | '/admin/new/ai'
    | '/api/ai/extract-image'
    | '/api/ai/extract-pdf'
    | '/api/ai/form-draft'
    | '/admin/forms-builder'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/admin/new'
    | '/api/health'
    | '/intake/complete'
    | '/intake/microphone'
    | '/intake/question'
    | '/admin/'
    | '/intake/'
    | '/admin/forms-builder/publish'
    | '/admin/new/ai'
    | '/api/ai/extract-image'
    | '/api/ai/extract-pdf'
    | '/api/ai/form-draft'
    | '/admin/forms-builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  IntakeCompleteRoute: typeof IntakeCompleteRoute
  IntakeMicrophoneRoute: typeof IntakeMicrophoneRoute
  IntakeQuestionRoute: typeof IntakeQuestionRoute
  AdminIndexRoute: typeof AdminIndexRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
  AdminFormsBuilderPublishRoute: typeof AdminFormsBuilderPublishRoute
  ApiAiExtractImageRoute: typeof ApiAiExtractImageRoute
  ApiAiExtractPdfRoute: typeof ApiAiExtractPdfRoute
  ApiAiFormDraftRoute: typeof ApiAiFormDraftRoute
  AdminFormsBuilderIndexRoute: typeof AdminFormsBuilderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/complete': {
      id: '/intake/complete'
      path: '/intake/complete'
      fullPath: '/intake/complete'
      preLoaderRoute: typeof IntakeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/microphone': {
      id: '/intake/microphone'
      path: '/intake/microphone'
      fullPath: '/intake/microphone'
      preLoaderRoute: typeof IntakeMicrophoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/question': {
      id: '/intake/question'
      path: '/intake/question'
      fullPath: '/intake/question'
      preLoaderRoute: typeof IntakeQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms-builder/': {
      id: '/admin/forms-builder/'
      path: '/admin/forms-builder'
      fullPath: '/admin/forms-builder/'
      preLoaderRoute: typeof AdminFormsBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms-builder/publish': {
      id: '/admin/forms-builder/publish'
      path: '/admin/forms-builder/publish'
      fullPath: '/admin/forms-builder/publish'
      preLoaderRoute: typeof AdminFormsBuilderPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new/ai': {
      id: '/admin/new/ai'
      path: '/ai'
      fullPath: '/admin/new/ai'
      preLoaderRoute: typeof AdminNewAiRouteImport
      parentRoute: typeof AdminNewRoute
    }
    '/api/ai/extract-image': {
      id: '/api/ai/extract-image'
      path: '/api/ai/extract-image'
      fullPath: '/api/ai/extract-image'
      preLoaderRoute: typeof ApiAiExtractImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/extract-pdf': {
      id: '/api/ai/extract-pdf'
      path: '/api/ai/extract-pdf'
      fullPath: '/api/ai/extract-pdf'
      preLoaderRoute: typeof ApiAiExtractPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/form-draft': {
      id: '/api/ai/form-draft'
      path: '/api/ai/form-draft'
      fullPath: '/api/ai/form-draft'
      preLoaderRoute: typeof ApiAiFormDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminNewRouteChildren {
  AdminNewAiRoute: typeof AdminNewAiRoute
}

const AdminNewRouteChildren: AdminNewRouteChildren = {
  AdminNewAiRoute: AdminNewAiRoute,
}

const AdminNewRouteWithChildren = AdminNewRoute._addFileChildren(
  AdminNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  IntakeCompleteRoute: IntakeCompleteRoute,
  IntakeMicrophoneRoute: IntakeMicrophoneRoute,
  IntakeQuestionRoute: IntakeQuestionRoute,
  AdminIndexRoute: AdminIndexRoute,
  IntakeIndexRoute: IntakeIndexRoute,
  AdminFormsBuilderPublishRoute: AdminFormsBuilderPublishRoute,
  ApiAiExtractImageRoute: ApiAiExtractImageRoute,
  ApiAiExtractPdfRoute: ApiAiExtractPdfRoute,
  ApiAiFormDraftRoute: ApiAiFormDraftRoute,
  AdminFormsBuilderIndexRoute: AdminFormsBuilderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
